#import "./../Fragments/Images/ImageArchive.gql"
#import "./Fragments/Page.gql"

query Pages(
  $after: String
  $parent: String
  $language: LanguageCodeFilterEnum
) {
  pages(
    after: $after
    where: {
      parent: $parent
      language: $language
      orderby: { field: MENU_ORDER, order: ASC }
    }
  ) {
    edges {
      node {
        ...page
        excerpt
        relativeUrl
        featuredImage {
          ...imageArchive
        }
      }
    }
  }
}
