#import "./../Fragments/ImageHero.gql"
#import "./Fragments/Page.gql"

query($uri: String, $pageId: Int) {
  page: pageBy(uri: $uri, pageId: $pageId) {
    ...page
    content
    featuredImage {
      ...imageHero
    }
    parent {
      ... on Page {
        pageId
      }
    }
  }
}
