#import "./Fragments/Page.gql"
#import "./../Fragments/Images/ImageRelated.gql"

query RelatedPages(
  $notIn: [ID]
  $parentId: ID
  $language: LanguageCodeFilterEnum
) {
  relatedPages: pages(
    where: {
      notIn: $notIn
      parent: $parentId
      language: $language
      orderby: { field: MENU_ORDER, order: ASC }
    }
  ) {
    edges {
      node {
        ...page
        relativeUrl
        featuredImage {
          ...imageSidebar
        }
      }
    }
  }
}
