#import "./Fragments/Page.gql"
#import "./../Fragments/Images/ImageRelated.gql"

query($notIn: [ID], $parentPageId: String, $language: LanguageCodeFilterEnum) {
  relatedPages: pages(
    where: { notIn: $notIn, parent: $parentPageId, language: $language }
  ) {
    edges {
      node {
        ...page
        relativeUrl
        featuredImage {
          ...imageRelated
        }
      }
    }
  }
}
