allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@vue/compiler-core@3.5.40'
  - '@vue/compiler-dom@3.5.40'
  - '@vue/compiler-sfc@3.5.40'
  - '@vue/compiler-ssr@3.5.40'
  - '@vue/reactivity@3.5.40'
  - '@vue/runtime-core@3.5.40'
  - '@vue/runtime-dom@3.5.40'
  - '@vue/server-renderer@3.5.40'
  - '@vue/shared@3.5.40'
  - vue@3.5.40
  - '@nuxt/scripts@1.3.2'
  - '@nuxtjs/i18n@10.5.0'
  - '@unhead/bundler@3.2.2'
  - '@unhead/vue@3.2.2'
  - unhead@3.2.2
onlyBuiltDependencies:
  - vue-demi
onlybuiltdependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver;
