#import "./Fragments/Room.gql"
#import "./../Fragments/Images/ImageRelated.gql"

query RelatedRooms($language: LanguageCodeFilterEnum, $notIn: [ID]) {
  relatedRooms: rooms(
    where: {
      language: $language
      notIn: $notIn
      orderby: { field: MENU_ORDER, order: ASC }
    }
  ) {
    edges {
      node {
        ...room
        uri: relativeUrl
        featuredImage {
          ...imageSidebar
        }
      }
    }
  }
}
