#import "./Fragments/Room.gql"

query($language: LanguageCodeFilterEnum, $notIn: [ID]) {
  relatedRooms: rooms(where: { language: $language, notIn: $notIn }) {
    edges {
      node {
        ...room
        relativeUrl
      }
    }
  }
}
