#import "./../Fragments/Images/ImageArchive.gql"
#import "./Fragments/Room.gql"

query($language: LanguageCodeFilterEnum) {
  rooms(first: 100, where: { language: $language }) {
    edges {
      node {
        ...room
        excerpt
        relativeUrl
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}
