#import "./../Fragments/Images/ImageHero.gql"
#import "./../Fragments/Images/Gallery.gql"
#import "./Fragments/Room.gql"

query Room($uri: ID!) {
  room(id: $uri, idType: SLUG) {
    ...room
    content
    featuredImage {
      ...imageHero
    }
    bookUrlGroup {
      bookUrl
    }
    galleryGroup {
      gallery {
        ...gallery
      }
    }
    pricesGroup {
      fullBoardHighSeason
      fullBoardLowSeason
      halfBoardHighSeason
      halfBoardLowSeason
    }
    services {
      edges {
        node {
          id
          name
        }
      }
    }
    translations {
      slug
      language {
        code
        slug
      }
    }
    seo {
      metaDesc
      opengraphDescription
      opengraphImage {
        archive: sourceUrl(size: ARCHIVE)
      }
      opengraphTitle
      title
      twitterDescription
      twitterImage {
        archive: sourceUrl(size: ARCHIVE)
      }
      twitterTitle    }
  }
}
