#import "./../Fragments/Images/ImageHero.gql"
#import "./Fragments/Post.gql"

query Post($uri: ID!) {
  post(id: $uri, idType: SLUG) {
    ...post
    date
    content
    featuredImage {
      ...imageHero
    }
    translations {
      slug
      language {
        code
        slug
      }
    }
    seo {
      metaDesc
      opengraphDescription
      opengraphImage {
        archive: sourceUrl(size: ARCHIVE)
      }
      opengraphTitle
      title
      twitterDescription
      twitterImage {
        archive: sourceUrl(size: ARCHIVE)
      }
      twitterTitle
    }
  }
}
