#import "./../Fragments/Images/ImageHero.gql"
#import "./Fragments/Post.gql"

query Post($uri: ID!) {
  post(id: $uri, idType: URI) {
    ...post
    date
    content
    featuredImage {
      ...imageHero
    }
  }
}
