#import "./../Fragments/Images/ImageArchive.gql"
#import "./Fragments/Post.gql"

query($after: String, $language: LanguageCodeFilterEnum) {
  posts(after: $after, where: { language: $language }) {
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        ...post
        date
        excerpt
        relativeUrl
        featuredImage {
          ...imageArchive
        }
      }
    }
  }
}
