#import "./../Fragments/Images/ImageHero.gql"
#import "./Fragments/Post.gql"

query($uri: String) {
  post: postBy(uri: $uri) {
    ...post
    date
    content
    featuredImage {
      ...imageHero
    }
  }
}
