#import "./Fragments/Post.gql"
#import "./../Fragments/Images/ImageRelated.gql"

query RelatedPosts($language: LanguageCodeFilterEnum, $notIn: [ID]) {
  relatedPosts: posts(where: { language: $language, notIn: $notIn }) {
    edges {
      node {
        ...post
        uri: relativeUrl
        featuredImage {
          ...imageSidebar
        }
      }
    }
  }
}
