fragment gallery on MediaItem {
  id
  altText
  galleryLarge: sourceUrl(size: HERO_LARGE)
  galleryMedium: sourceUrl(size: HERO_MEDIUM)
  gallerySmall: sourceUrl(size: HERO_SMALL)
  galleryExtraSmall: sourceUrl(size: ARCHIVE)
  galleryLargeWebP: sourceUrlWebP(size: HERO_LARGE)
  galleryMediumWebP: sourceUrlWebP(size: HERO_MEDIUM)
  gallerySmallWebP: sourceUrlWebP(size: HERO_SMALL)
  galleryExtraSmallWebP: sourceUrlWebP(size: ARCHIVE)
  galleryLargeAvif: sourceUrlAvif(size: HERO_LARGE)
  galleryMediumAvif: sourceUrlAvif(size: HERO_MEDIUM)
  gallerySmallAvif: sourceUrlAvif(size: HERO_SMALL)
  galleryExtraSmallAvif: sourceUrlAvif(size: ARCHIVE)
}
