fragment gallery on MediaItem {
  id
  altText
  galleryLarge: sourceUrl(size: HERO_LARGE)
  galleryMedium: sourceUrl(size: HERO_MEDIUM)
  gallerySmall: sourceUrl(size: HERO_SMALL)
  galleryExtraSmall: sourceUrl(size: ARCHIVE)
}
