fragment imageHero on NodeWithFeaturedImageToMediaItemConnectionEdge {
  node {
    altText
    heroLarge: sourceUrl(size: HERO_LARGE)
    heroMedium: sourceUrl(size: HERO_MEDIUM)
    heroSmall: sourceUrl(size: HERO_SMALL)
    heroLargeWebP: sourceUrlWebP(size: HERO_LARGE)
    heroMediumWebP: sourceUrlWebP(size: HERO_MEDIUM)
    heroSmallWebP: sourceUrlWebP(size: HERO_SMALL)
  }
}
