fragment imageSidebar on NodeWithFeaturedImageToMediaItemConnectionEdge {
  node {
    altText
    related: sourceUrl(size: RELATED)
    related2x: sourceUrl(size: RELATED_2X)
    relatedWebP: sourceUrlWebP(size: RELATED)
    relatedWebP2x: sourceUrlWebP(size: RELATED_2X)
    relatedAvif: sourceUrlAvif(size: RELATED)
    relatedAvif2x: sourceUrlAvif(size: RELATED_2X)
  }
}
