#import "./../Fragments/Images/ImageHero.gql"
#import "./../Fragments/Seo.gql"
#import "./Fragments/Arrangement.gql"

query Arrangement($uri: ID!) {
  arrangement(id: $uri, idType: SLUG) {
    ...arrangement
    content
    featuredImage {
      ...imageHero
    }
    pricesGroup {
      prices {
        label
        value
        nights
        adults
        kids
        extraNight
      }
    }
    translations {
      slug
      language {
        code
        slug
      }
    }
    seo {
      ...seo
    }
  }
}
