#import "./../Fragments/Images/ImageArchive.gql"
#import "./Fragments/Arrangement.gql"

query($language: LanguageCodeFilterEnum) {
  arrangements(first: 100, where: { language: $language }) {
    edges {
      node {
        ...arrangement
        excerpt
        relativeUrl
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}
