#import "./../Fragments/Images/ImageHero.gql"
#import "./Fragments/Arrangement.gql"

query($uri: ID!) {
  arrangement(id: $uri, idType: URI) {
    ...arrangement
    content
    featuredImage {
      ...imageHero
    }
    pricesGroup {
      prices {
        label
        value
      }
    }
  }
}
