#import "./../Fragments/Images/ImageHero.gql"
#import "./Fragments/Arrangement.gql"

query($uri: String) {
  arrangement: arrangementBy(uri: $uri) {
    ...arrangement
    content
    featuredImage {
      ...imageHero
    }
    pricesGroup {
      prices {
        label
        value
      }
    }
  }
}
