#import "./Fragments/Arrangement.gql"
#import "./../Fragments/Images/ImageSidebar.gql"

query($language: LanguageCodeFilterEnum, $notIn: [ID]) {
  relatedArrangements: arrangements(
    where: { language: $language, notIn: $notIn }
  ) {
    edges {
      node {
        ...arrangement
        relativeUrl
        featuredImage {
          ...imageSidebar
        }
      }
    }
  }
}
