#import "./Fragments/Arrangement.gql"
#import "./../Fragments/Images/ImageRelated.gql"

query RelatedArrangements($language: LanguageCodeFilterEnum, $notIn: [ID]) {
  relatedArrangements: arrangements(
    where: {
      language: $language
      notIn: $notIn
      orderby: { field: MENU_ORDER, order: ASC }
    }
  ) {
    edges {
      node {
        ...arrangement
        relativeUrl
        featuredImage {
          ...imageSidebar
        }
      }
    }
  }
}
