fragment lastMinute on Page {
  lastMinute {
    lastMinuteRooms {
      room {
        ... on Room {
          title
        }
      }
     totalPersons {
        adults
        kids
      }      
      dates {
        dateFrom
        dateUntill
      }
      price
      sold
    }
  }
}