#import "./../../Fragments/Images/ImageHero.gql"
#import "./../../Fragments/Images/Gallery.gql"
#import "./Page.gql"

fragment pageDetails on Page {
  ...page
  content
  link
  featuredImage {
    ...imageHero
  }
  galleryGroup {
    gallery {
      ...gallery
    }
  }
  parentDatabaseId
  seo {
    metaDesc
    opengraphDescription
    opengraphImage {
      archive: sourceUrl(size: ARCHIVE)
    }
    opengraphTitle
    title
    twitterDescription
    twitterImage {
      archive: sourceUrl(size: ARCHIVE)
    }
    twitterTitle
  }
}
