query($language: LanguageCodeFilterEnum, $hotelPageId: ID!) {
  hotel: page(id: $hotelPageId, idType: DATABASE_ID) {
    title
    relativeUrl
    childPages {
      edges {
        node {
          id
          relativeUrl
          title
        }
      }
    }
  }
  rooms(where: { language: $language }) {
    edges {
      node {
        id
        relativeUrl
        title
      }
    }
  }
  arrangements(where: { language: $language }) {
    edges {
      node {
        id
        relativeUrl
        title
      }
    }
  }
}
