fragment menuItem on Page {
  id
  uri
  title
}

query Menu(
  $language: LanguageCodeFilterEnum
  $hotelPageId: ID!
  $environmentPageId: ID!
  $kidsPageId: ID!
) {
  hotel: page(id: $hotelPageId, idType: DATABASE_ID) {
    ...menuItem
  }
  environment: page(id: $environmentPageId, idType: DATABASE_ID) {
    ...menuItem
  }
  kids: page(id: $kidsPageId, idType: DATABASE_ID) {
    ...menuItem
  }
  hotelPageChildren: pages(
    where: { parent: $hotelPageId, orderby: { field: MENU_ORDER, order: ASC } }
  ) {
    edges {
      node {
        ...menuItem
      }
    }
  }
  environmentPageChildren: pages(
    where: {
      parent: $environmentPageId
      orderby: { field: MENU_ORDER, order: ASC }
    }
  ) {
    edges {
      node {
        ...menuItem
      }
    }
  }
  kidsPageChildren: pages(
    where: { parent: $kidsPageId, orderby: { field: MENU_ORDER, order: ASC } }
  ) {
    edges {
      node {
        ...menuItem
      }
    }
  }
  rooms(
    where: { language: $language, orderby: { field: MENU_ORDER, order: ASC } }
  ) {
    edges {
      node {
        id
        uri: relativeUrl
        title
      }
    }
  }
  arrangements(
    where: { language: $language, orderby: { field: MENU_ORDER, order: ASC } }
  ) {
    edges {
      node {
        id
        uri: relativeUrl
        title
      }
    }
  }
  menuItems(where: { location: HEADER, language: $language }) {
    edges {
      node {
        id
        title: label
        uri: path
        childItems {
          edges {
            node {
              title: label
              uri: path
            }
          }
        }
      }
    }
  }
  lastMinutes(where: { language: $language }) {
    edges {
      node {
        id
      }
    }
  }
}
