fragment seo on SEO {
  metaDesc
  opengraphDescription
  opengraphImage {
    archive: sourceUrl(size: ARCHIVE)
  }
  opengraphTitle
  title
  twitterDescription
  twitterImage {
    archive: sourceUrl(size: ARCHIVE)
  }
  twitterTitle
}
