#import "./Fragments/ImageArchive.gql"

query getArrangements($language: LanguageCodeFilterEnum) {
  arrangementsHighlights: arrangements(first: 3, where: { language: $language }) {
    edges {
      node {
        id
        title
        excerpt
        relativeUrl
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}
