#import "./Fragments/ImageArchive.gql"

query getArrangements($language: LanguageCodeFilterEnum) {
  arrangements(first: 100, where: { language: $language }) {
    edges {
      node {
        id
        title
        excerpt
        link
        relativeUrl
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}
