#import "./Fragments/ImageHero.gql"
#import "./Fragments/Arrangement.gql"

query GET_ARRANGEMENT_BY_URI($uri: String) {
  arrangement: arrangementBy(uri: $uri) {
    ...arrangement
    arrangementId
    content
    featuredImage {
      ...imageHero
    }
    pricesGroup {
      prices {
        label
        value
      }
    }
  }
}
