#import "./Fragments/ImageHero.gql"

query GET_ARRANGEMENT_BY_URI($uri: String) {
  arrangement: arrangementBy(uri: $uri) {
    id
    arrangementId
    title
    content
    featuredImage {
      ...imageHero
    }
    pricesGroup {
 			prices {
 			  label
 			  value
 			}
    }
  }
}
