#import "./Fragments/ImageArchive.gql"

query getArrangements {
  arrangementsHighlights: arrangements(first: 3) {
    edges {
      node {
        id
        title
        excerpt
        link
        slug
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}
