#import "./Fragments/ImageArchive.gql"

query getArrangements {
  arrangements(first: 100) {
    edges {
      node {
        id
        title
        excerpt
        slug
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}

