query($language: LanguageCodeFilterEnum) {
  rooms(where: {language: $language}) {
    edges {
      node {
        id
        relativeUrl
        title
      }
    }
  }
  arrangements(where: {language: $language}) {
    edges {
      node {
        id
        relativeUrl
        title
      }
    }
  }
}
