#import "./Fragments/PageContent.gql"
#import "./Fragments/ImageHero.gql"

query GET_PAGE_BY_URI($pageId: Int) {
  page: pageBy(pageId: $pageId) {
    ...pageContent
    forStudentsAndParentsGroup {
      student {
        text
      }
      parents {
        text
      }
    }
    pricesGroup {
      image {
        ...imageHero
      }
      prices {
        price
        title
        recommended
      }
    }
  }
}
