#import "./Fragments/PageContent.gql"
#import "./Fragments/ImageArchive.gql"

query GET_TEACHERS_PAGE_BY_URI($pageId: Int) {
  page: pageBy(pageId: $pageId) {
    ...pageContent
    employersGroup {
      employers {
        bio
        facebook
        fieldGroupName
        linkedin
        name
        twitter
        image {
          ...imageArchive
        }
      }
    }
    videosGroup {
      video1
      video2
    }
  }
}
