#import "./Fragments/Arrangement.gql"

query getArrangements($notIn: [ID]) {
  relatedArrangements: arrangements(where: { notIn: $notIn }) {
    edges {
      node {
        ...arrangement
        slug
      }
    }
  }
}
