#import "./Fragments/Arrangement.gql"

query getArrangements($language: LanguageCodeFilterEnum, $notIn: [ID]) {
  relatedArrangements: arrangements(where: { language: $language, notIn: $notIn }) {
    edges {
      node {
        ...arrangement
        slug
      }
    }
  }
}
