query getArrangements($language: LanguageCodeFilterEnum, $notIn: [ID]) {
  relatedRooms: rooms(where: { language: $language, notIn: $notIn }) {
    edges {
      node {
        id
        title
        relativeUrl
      }
    }
  }
}
