#import "./Fragments/ImageHero.gql"
#import "./Fragments/Room.gql"

query($uri: String) {
  room: roomBy(uri: $uri) {
    ...room
    content
    featuredImage {
      ...imageHero
    }
    bookUrlGroup {
      bookUrl
    }
    galleryGroup {
      gallery {
        id
        altText
        heroLarge: sourceUrl(size: HERO_LARGE)
        heroMedium: sourceUrl(size: HERO_MEDIUM)
        heroSmall: sourceUrl(size: HERO_SMALL)
      }
    }
    pricesGroup {
      fullBoardHighSeason
      fullBoardLowSeason
      halfBoardHighSeason
      halfBoardLowSeason
    }
    services {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
