#import "./Fragments/ImageArchive.gql"

query getRooms($language: LanguageCodeFilterEnum,) {
  rooms(first: 100, where: { language: $language }) {
    edges {
      node {
        id
        title
        excerpt
        relativeUrl
        slug
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}
