#import "./Fragments/ImageArchive.gql"

query getRooms($language: LanguageCodeFilterEnum) {
  rooms(first: 100, where: { language: $language }) {
    edges {
      node {
        id
        roomId
        title
        excerpt
        relativeUrl
        featuredImage {
          ...imageArchive
        }
        pricesGroup {
          priceFrom
        }
      }
    }
  }
}
