#import "./../Fragments/Images/ImageArchive.gql"

query GetLastMinutes($language: LanguageCodeFilterEnum) {
  lastMinutes(
    where: { language: $language, orderby: { field: MENU_ORDER, order: ASC } }
  ) {
    edges {
      node {
        id
        title
        servicesLastMinute {
          edges {
            node {
              name
            }
          }
        }
        featuredImage {
          ...imageArchive
        }

        lastMinute {
          totalPersons {
            adults
            kids
          }
          dates {
            dateFrom
            dateUntill
          }
          fieldGroupName
          price
          room {
            ... on Room {
              uri: relativeUrl
              title
            }
          }
        }
      }
    }
  }
}
