#import "./../Fragments/Images/ImageArchive.gql"

query GetLastMinutes {
  lastMinutes {
    edges {
      node {
        id
        title
        featuredImage {
          ...imageArchive
        }

        lastMinute {
          totalPersons {
            adults
            kids
          }
          dates {
            dateFrom
            dateUntill
          }
          fieldGroupName
          price
          sold
          room {
            ... on Room {
              title
            }
          }
        }
      }
    }
  }
}
